In [1]:
import pandas as pd
import numpy as np

In [2]:
fighters = pd.read_csv('../CSV_Files/Fighters.csv')
fighters

,Name,Age,Height,Reach,Wins,Losses,SLpM,Str. Acc,Str. Def,SApM,TD Avg.,TD Acc.,TD Def.,Sub avg.
0,Khamzat Chimaev,31,188,191,15,0,4.04,0.60,0.43,2.32,5.29,0.55,0.85,1.8
1,Dricus du Plessis,32,186,193,23,3,5.18,0.48,0.52,4.33,2.22,0.51,0.34,0.7
2,Robert Whittaker,35,183,185,27,9,4.39,0.43,0.59,3.36,0.73,0.38,0.82,0.0
3,Kamaru Usman,38,183,193,21,4,4.16,0.51,0.55,2.67,2.79,0.44,0.89,0.1
4,Kevin Holland,33,192,205,28,15,4.26,0.49,0.50,3.22,0.83,0.39,0.56,0.5
5,Gilbert Burns,39,178,180,22,9,3.15,0.48,0.52,3.64,2.12,0.37,0.53,0.5
6,Li Jingliang,38,183,180,19,9,4.46,0.42,0.56,3.95,1.19,0.41,0.60,0.0
7,Gerald Meerschaert,38,186,196,37,21,3.01,0.45,0.53,3.52,1.82,0.30,0.42,1.4
8,Rhys McKee,30,188,198,14,7,4.71,0.40,0.47,7.15,0.00,0.00,0.47,0.0
9,John Phillips,40,180,190,22,11,1.72,0.34,0.49,4.03,0.00,0.00,0.07,0.0
10,Sean Strickland,35,185,193,30,7,6.04,0.42,0.60,4.57,0.71,0.64,0.76,0.2
11,Anthony Hernandez,32,183,190,15,3,4.57,0.60,0.51,3.10,5.88,0.48,0.68,1.6
12,Paulo Costa,35,186,183,15,4,6.26,0.58,0.49,6.20,0.32,0.50,0.80,0.0
13,Israel Adesanya,36,193,203,24,6,4.03,0.48,0.55,3.22,0.05,0.09,0.76,0.1
14,Abus Magomedov,35,188,198,28,7,3.07,0.49,0.55,3.43,2.61,0.59,1.00,0.4
15,Nassourdine Imavov,30,191,191,17,4,4.28,0.54,0.58,3.17,0.74,0.32,0.81,1.0
16,Jared Cannonier,42,180,196,18,9,4.42,0.49,0.56,4.35,0.54,0.40,0.64,0.0
17,Alex Pereira,38,193,201,13,3,5.16,0.62,0.53,3.50,0.11,0.50,0.79,0.2
18,Jack Hermansson,37,185,196,24,10,5.15,0.45,0.56,3.72,1.48,0.29,0.80,0.4
19,Uriah Hall,41,183,201,18,11,3.23,0.48,0.54,3.85,0.54,0.38,0.64,0.1
20,Krzysztof Jotko,36,185,198,24,6,2.98,0.42,0.57,2.23,1.33,0.39,0.82,0.1
21,Brendan Allen,30,188,191,26,7,3.59,0.53,0.47,3.62,1.56,0.42,0.56,1.1
22,Jack Marshman,36,183,185,23,10,2.74,0.25,0.56,4.19,0.00,0.00,0.20,0.0
23,Nordine Taleb,44,185,188,15,7,3.66,0.51,0.66,2.62,1.94,0.76,0.73,0.0
24,Elizeu Zaleski dos Santos,39,180,185,25,10,4.16,0.41,0.55,3.56,0.79,0.20,0.67,0.4
25,Court McGee,41,180,191,23,14,4.50,0.36,0.60,3.65,1.78,0.24,0.70,0.5
26,Tom Breese,34,191,185,12,3,3.34,0.50,0.60,2.81,0.00,0.00,0.70,1.1
27,Igor Araujo,45,185,193,25,9,1.52,0.42,0.49,2.86,0.86,0.15,0.22,0.6
28,Alex Garcia,38,175,183,15,6,1.81,0.31,0.59,3.03,3.72,0.52,0.66,0.1
29,Santiago Ponzinibbio,39,183,185,31,9,4.78,0.41,0.61,4.68,0.60,0.27,0.71,0.0
30,Luke Barnatt,38,198,196,13,4,4.43,0.36,0.59,3.87,0.63,0.42,0.63,0.4
31,Robert McDaniel,42,191,191,28,10,1.64,0.44,0.56,1.98,0.93,0.50,0.50,1.4

In [3]:
ChimaevFight = pd.read_csv('../CSV_Files/ChimaevFights.csv')
ChimaevFight

,Fight,Belt,KO/TKO/Submission,Time,Sig. Str.,Sig. Str. B,Sig. Str. %,TD,TD %,CTRL,TD B,TD % B,CTRL B,Won
0,Dricus Du Plessis,1,0,25.0,37,13,0.78,12,0.70,21.7,1,1.0,0.9,1
1,Robert Whittaker,0,1,3.6,3,2,0.75,2,0.50,3.3,0,0.0,0.0,1
2,Kamaru Usman,0,0,15.0,38,36,0.54,4,0.33,7.3,0,0.0,0.0,1
3,Kevin Holland,0,1,2.2,0,0,0.00,2,0.40,1.9,0,0.0,0.0,1
4,Gilbert Burns,0,0,15.0,108,119,0.48,2,0.66,2.4,0,0.0,0.0,1
5,Li Jingliang,0,1,3.3,25,0,1.00,1,0.50,3.0,0,0.0,0.0,1
6,Gerald Meerschaert,0,1,0.3,4,0,0.66,0,0.00,0.0,0,0.0,0.0,1
7,Rhys McKee,0,1,3.2,40,0,0.64,1,0.50,3.0,0,0.0,0.0,1
8,John Phillips,0,1,6.2,43,1,0.82,2,1.00,5.9,0,0.0,0.0,1

In [4]:
StricklandFight = pd.read_csv('../CSV_Files/StricklandFights.csv')
StricklandFight

,Fight,Belt,KO/TKO/Submission,Time,Sig. Str.,Sig. Str. B,Sig. Str. %,TD,TD %,CTRL,TD B,TD % B,CTRL B,Won
0,Anthony Hernandez,0,1,12.4,110,55,0.45,0,0.00,0.3,0,0.00,0.5,1
1,Dricus Du Plessis,1,0,25.0,128,147,0.46,1,0.50,0.1,1,0.50,0.1,0
2,Paulo Costa,0,0,25.0,182,158,0.45,0,0.00,0.0,0,0.00,0.0,1
3,Dricus Du Plessis,1,0,25.0,173,137,0.42,0,0.00,0.0,6,0.54,2.1,0
4,Israel Adesanya,1,0,25.0,137,94,0.52,0,0.00,0.2,0,0.00,0.0,1
5,Abus Magomedov,0,1,14.3,81,47,0.43,0,0.00,0.2,1,0.50,0.4,1
6,Nassourdine Imavov,0,0,25.0,182,123,0.44,1,1.00,4.2,0,0.00,0.2,1
7,Jared Cannonier,0,0,25.0,152,141,0.38,0,0.00,0.0,1,1.00,0.8,0
8,Alex Pereira,0,1,2.6,15,25,0.51,0,0.00,0.0,0,0.00,0.0,0
9,Jack Hermansson,0,0,25.0,153,137,0.46,0,0.00,0.0,0,0.00,0.5,1
10,Urial Hall,0,0,25.0,186,107,0.43,4,0.66,7.0,0,0.00,0.0,1
11,Kryzystof Jotko,0,0,15.0,84,37,0.46,0,0.00,0.0,0,0.00,0.0,1
12,Brendan Allen,0,1,6.5,94,51,0.58,1,1.00,1.6,0,0.00,0.0,1
13,Jack Marshman,0,0,15.0,106,48,0.46,0,0.00,0.0,0,0.00,0.0,1
14,Nordine Taleb,0,1,8.2,65,48,0.36,0,0.00,0.6,0,0.00,0.0,1
15,Elizeu Zaleski,0,1,3.7,14,15,0.38,0,0.00,0.0,0,0.00,0.1,0
16,Court McGee,0,0,15.0,78,62,0.30,3,1.00,2.7,0,0.00,1.7,1
17,Kamaru Usman,0,0,15.0,27,90,0.26,0,0.00,0.0,2,0.25,8.1,0
18,Tom Breese,0,0,15.0,73,62,0.35,0,0.00,0.3,0,0.00,0.2,1
19,Alex Garcia,0,1,14.4,84,23,0.48,1,0.50,2.8,3,0.42,3.5,1
20,Igor Araujo,0,0,15.0,71,39,0.42,3,1.00,5.5,0,0.00,0.3,1
21,Santiago Ponzinibbio,0,0,15.0,44,50,0.26,2,0.50,1.4,1,0.33,0.5,0
22,Luke Barnatt,0,0,15.0,48,44,0.29,1,0.33,0.7,0,0.00,0.5,1
23,Robert McDaniel,0,1,4.5,20,4,0.57,1,0.50,2.6,1,1.00,0.4,1

In [17]:
ChimaevDS = fighters[fighters['Name'] == 'Khamzat Chimaev']
StricklandDS = fighters[fighters['Name'] == 'Sean Strickland']

for i in range(1,14):
    ChimaevDS.insert(i+13, ChimaevFight.columns[i], 0)
    StricklandDS.insert(i+13, StricklandFight.columns[i], 0)

In [18]:
columns_names = list(fighters.columns) + [col for col in ChimaevFight.columns if col != 'Fight']

for i in range(0, 9):
    data = list(fighters.iloc[i+1, :]) + list(ChimaevFight.iloc[i, 1::])
    dataframe = pd.DataFrame(data, index=columns_names).transpose()
    ChimaevDS = pd.concat([ChimaevDS, dataframe])

ChimaevDS = ChimaevDS.reset_index(drop=True)
ChimaevDS

,Name,Age,Height,Reach,Wins,Losses,SLpM,Str. Acc,Str. Def,SApM,...,Sig. Str.,Sig. Str. B,Sig. Str. %,TD,TD %,CTRL,TD B,TD % B,CTRL B,Won
0,Khamzat Chimaev,31,188,191,15,0,4.04,0.6,0.43,2.32,...,0,0,0,0,0,0,0,0,0,0
1,Dricus du Plessis,32,186,193,23,3,5.18,0.48,0.52,4.33,...,37,13,0.78,12,0.7,21.7,1,1.0,0.9,1
2,Robert Whittaker,35,183,185,27,9,4.39,0.43,0.59,3.36,...,3,2,0.75,2,0.5,3.3,0,0.0,0.0,1
3,Kamaru Usman,38,183,193,21,4,4.16,0.51,0.55,2.67,...,38,36,0.54,4,0.33,7.3,0,0.0,0.0,1
4,Kevin Holland,33,192,205,28,15,4.26,0.49,0.5,3.22,...,0,0,0.0,2,0.4,1.9,0,0.0,0.0,1
5,Gilbert Burns,39,178,180,22,9,3.15,0.48,0.52,3.64,...,108,119,0.48,2,0.66,2.4,0,0.0,0.0,1
6,Li Jingliang,38,183,180,19,9,4.46,0.42,0.56,3.95,...,25,0,1.0,1,0.5,3.0,0,0.0,0.0,1
7,Gerald Meerschaert,38,186,196,37,21,3.01,0.45,0.53,3.52,...,4,0,0.66,0,0.0,0.0,0,0.0,0.0,1
8,Rhys McKee,30,188,198,14,7,4.71,0.4,0.47,7.15,...,40,0,0.64,1,0.5,3.0,0,0.0,0.0,1
9,John Phillips,40,180,190,22,11,1.72,0.34,0.49,4.03,...,43,1,0.82,2,1.0,5.9,0,0.0,0.0,1

In [19]:
data = list(fighters.iloc[11, :]) + list(StricklandFight.iloc[0, 1::])
df = pd.DataFrame(data, index=columns_names).transpose()
StricklandDS = pd.concat([StricklandDS, df])

data = list(fighters.iloc[1, :]) + list(StricklandFight.iloc[1, 1::])
df = pd.DataFrame(data, index=columns_names).transpose()
StricklandDS = pd.concat([StricklandDS, df])

data = list(fighters.iloc[12, :]) + list(StricklandFight.iloc[2, 1::])
df = pd.DataFrame(data, index=columns_names).transpose()
StricklandDS = pd.concat([StricklandDS, df])

data = list(fighters.iloc[1, :]) + list(StricklandFight.iloc[3, 1::])
df = pd.DataFrame(data, index=columns_names).transpose()
StricklandDS = pd.concat([StricklandDS, df])

for i in range(4, 17):
    data = list(fighters.iloc[i+9, :]) + list(StricklandFight.iloc[i, 1::])
    df = pd.DataFrame(data, index=columns_names).transpose()
    StricklandDS = pd.concat([StricklandDS, df])

data = list(fighters.iloc[3, :]) + list(StricklandFight.iloc[17, 1::])
df = pd.DataFrame(data, index=columns_names).transpose()
StricklandDS = pd.concat([StricklandDS, df])

for i in range(18, 24):
    data = list(fighters.iloc[i+8, :]) + list(StricklandFight.iloc[i, 1::])
    df = pd.DataFrame(data, index=columns_names).transpose()
    StricklandDS = pd.concat([StricklandDS, df])

StricklandDS = StricklandDS.reset_index(drop=True)
StricklandDS

,Name,Age,Height,Reach,Wins,Losses,SLpM,Str. Acc,Str. Def,SApM,...,Sig. Str.,Sig. Str. B,Sig. Str. %,TD,TD %,CTRL,TD B,TD % B,CTRL B,Won
0,Sean Strickland,35,185,193,30,7,6.04,0.42,0.6,4.57,...,0,0,0,0,0,0,0,0,0,0
1,Anthony Hernandez,32,183,190,15,3,4.57,0.6,0.51,3.1,...,110,55,0.45,0,0.0,0.3,0,0.0,0.5,1
2,Dricus du Plessis,32,186,193,23,3,5.18,0.48,0.52,4.33,...,128,147,0.46,1,0.5,0.1,1,0.5,0.1,0
3,Paulo Costa,35,186,183,15,4,6.26,0.58,0.49,6.2,...,182,158,0.45,0,0.0,0.0,0,0.0,0.0,1
4,Dricus du Plessis,32,186,193,23,3,5.18,0.48,0.52,4.33,...,173,137,0.42,0,0.0,0.0,6,0.54,2.1,0
5,Israel Adesanya,36,193,203,24,6,4.03,0.48,0.55,3.22,...,137,94,0.52,0,0.0,0.2,0,0.0,0.0,1
6,Abus Magomedov,35,188,198,28,7,3.07,0.49,0.55,3.43,...,81,47,0.43,0,0.0,0.2,1,0.5,0.4,1
7,Nassourdine Imavov,30,191,191,17,4,4.28,0.54,0.58,3.17,...,182,123,0.44,1,1.0,4.2,0,0.0,0.2,1
8,Jared Cannonier,42,180,196,18,9,4.42,0.49,0.56,4.35,...,152,141,0.38,0,0.0,0.0,1,1.0,0.8,0
9,Alex Pereira,38,193,201,13,3,5.16,0.62,0.53,3.5,...,15,25,0.51,0,0.0,0.0,0,0.0,0.0,0
10,Jack Hermansson,37,185,196,24,10,5.15,0.45,0.56,3.72,...,153,137,0.46,0,0.0,0.0,0,0.0,0.5,1
11,Uriah Hall,41,183,201,18,11,3.23,0.48,0.54,3.85,...,186,107,0.43,4,0.66,7.0,0,0.0,0.0,1
12,Krzysztof Jotko,36,185,198,24,6,2.98,0.42,0.57,2.23,...,84,37,0.46,0,0.0,0.0,0,0.0,0.0,1
13,Brendan Allen,30,188,191,26,7,3.59,0.53,0.47,3.62,...,94,51,0.58,1,1.0,1.6,0,0.0,0.0,1
14,Jack Marshman,36,183,185,23,10,2.74,0.25,0.56,4.19,...,106,48,0.46,0,0.0,0.0,0,0.0,0.0,1
15,Nordine Taleb,44,185,188,15,7,3.66,0.51,0.66,2.62,...,65,48,0.36,0,0.0,0.6,0,0.0,0.0,1
16,Elizeu Zaleski dos Santos,39,180,185,25,10,4.16,0.41,0.55,3.56,...,14,15,0.38,0,0.0,0.0,0,0.0,0.1,0
17,Court McGee,41,180,191,23,14,4.5,0.36,0.6,3.65,...,78,62,0.3,3,1.0,2.7,0,0.0,1.7,1
18,Kamaru Usman,38,183,193,21,4,4.16,0.51,0.55,2.67,...,27,90,0.26,0,0.0,0.0,2,0.25,8.1,0
19,Tom Breese,34,191,185,12,3,3.34,0.5,0.6,2.81,...,73,62,0.35,0,0.0,0.3,0,0.0,0.2,1
20,Igor Araujo,45,185,193,25,9,1.52,0.42,0.49,2.86,...,84,23,0.48,1,0.5,2.8,3,0.42,3.5,1
21,Alex Garcia,38,175,183,15,6,1.81,0.31,0.59,3.03,...,71,39,0.42,3,1.0,5.5,0,0.0,0.3,1
22,Santiago Ponzinibbio,39,183,185,31,9,4.78,0.41,0.61,4.68,...,44,50,0.26,2,0.5,1.4,1,0.33,0.5,0
23,Luke Barnatt,38,198,196,13,4,4.43,0.36,0.59,3.87,...,48,44,0.29,1,0.33,0.7,0,0.0,0.5,1
24,Robert McDaniel,42,191,191,28,10,1.64,0.44,0.56,1.98,...,20,4,0.57,1,0.5,2.6,1,1.0,0.4,1

In [20]:
columns_names

['Name',
 'Age',
 'Height',
 'Reach',
 'Wins',
 'Losses',
 'SLpM',
 'Str. Acc',
 'Str. Def',
 'SApM',
 'TD Avg.',
 'TD Acc.',
 'TD Def.',
 'Sub avg.',
 'Belt',
 'KO/TKO/Submission',
 'Time',
 'Sig. Str. ',
 'Sig. Str. B',
 'Sig. Str. %',
 'TD',
 'TD %',
 'CTRL',
 'TD B',
 'TD % B',
 'CTRL B',
 'Won']

In [26]:
StricklandDS = StricklandDS.infer_objects()
ChimaevDS = ChimaevDS.infer_objects()